from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Especialidade(models.Model):
    ESPECIALIDADE = [
        ('ACUPUNTURA', 'ACUPUNTURA'), ('ALERGIA E IMUNOLOGIA', 'ALERGIA E IMUNOLOGIA'), ('ANESTESIOLOGIA', 'ANESTESIOLOGIA'),
        ('ANGIOLOGIA', 'ANGIOLOGIA'), ('CANCEROLOGIA CLÍNICA', 'CANCEROLOGIA CLÍNICA'), ('CANCEROLOGIA CIRÚRGICA', 'CANCEROLOGIA CIRÚRGICA'),
        ('CANCEROLOGIA PEDIÁTRICA', 'CANCEROLOGIA PEDIÁTRICA'), ('CARDIOLOGIA', 'CARDIOLOGIA'), ('CIRURGIA CARDIOVASCULAR', 'CIRURGIA CARDIOVASCULAR'),
        ('CIRURGIA DE CABEÇA E PESCOÇO', 'CIRURGIA DE CABEÇA E PESCOÇO'), ('CIRURGIA DO APARELHO DIGESTIVO', 'CIRURGIA DO APARELHO DIGESTIVO'),
        ('CIRURGIA GERAL', 'CIRURGIA GERAL'), ('CIRURGIA PEDIÁTRICA', 'CIRURGIA PEDIÁTRICA'), ('CIRURGIA PLÁSTICA', 'CIRURGIA PLÁSTICA'),
        ('CIRURGIA TORÁCICA', 'CIRURGIA TORÁCICA'), ('CIRURGIA VASCULAR', 'CIRURGIA VASCULAR'), ('CLÍNICA MÉDICA', 'CLÍNICA MÉDICA'),
        ('COLOPROCTOLOGIA', 'COLOPROCTOLOGIA'), ('DERMATOLOGIA', 'DERMATOLOGIA'), ('ENDOCRINOLOGIA', 'ENDOCRINOLOGIA'),
        ('ENDOSCOPIA', 'ENDOSCOPIA'), ('GASTROENTEROLOGIA', 'GASTROENTEROLOGIA'), ('GENÉTICA MÉDICA', 'GENÉTICA MÉDICA'),
        ('GERIATRIA', 'GERIATRIA'), ('GINECOLOGIA E OBSTETRÍCIA', 'GINECOLOGIA E OBSTETRÍCIA'), ('HEMATOLOGIA E HEMOTERAPIA', 'HEMATOLOGIA E HEMOTERAPIA'),
        ('HOMEOPATIA', 'HOMEOPATIA'), ('INFECTOLOGIA', 'INFECTOLOGIA'), ('MASTOLOGIA', 'MASTOLOGIA'),
        ('MEDICINA DE FAMÍLIA E COMUNIDADE', 'MEDICINA DE FAMÍLIA E COMUNIDADE'), ('MEDICINA DO TRABALHO', 'MEDICINA DO TRABALHO'),
        ('MEDICINA DO TRÁFEGO', 'MEDICINA DO TRÁFEGO'), ('MEDICINA ESPORTIVA', 'MEDICINA ESPORTIVA'),
        ('MEDICINA FÍSICA E REABILITAÇÃO', 'MEDICINA FÍSICA E REABILITAÇÃO'), ('MEDICINA INTENSIVA', 'MEDICINA INTENSIVA'),
        ('MEDICINA LEGAL', 'MEDICINA LEGAL'), ('MEDICINA NUCLEAR', 'MEDICINA NUCLEAR'), ('MEDICINA PREVENTIVA E SOCIAL', 'MEDICINA PREVENTIVA E SOCIAL'),
        ('NEFROLOGIA', 'NEFROLOGIA'), ('NEUROCIRURGIA', 'NEUROCIRURGIA'), ('NEUROLOGIA', 'NEUROLOGIA'), ('NUTROLOGIA', 'NUTROLOGIA'),
        ('OFTALMOLOGIA', 'OFTALMOLOGIA'), ('ORTOPEDIA e TRAUMATOLOGIA', 'ORTOPEDIA e TRAUMATOLOGIA'), ('OTORRINOLARINGOLOGIA', 'OTORRINOLARINGOLOGIA'),
        ('PATOLOGIA', 'PATOLOGIA'), ('PATOLOGIA CLÍNICA/MEDICINA LABORATORIAL', 'PATOLOGIA CLÍNICA/MEDICINA LABORATORIAL'),
        ('PEDIATRIA', 'PEDIATRIA'), ('PNEUMOLOGIA', 'PNEUMOLOGIA'), ('PSIQUIATRIA', 'PSIQUIATRIA'),
        ('RADIOLOGIA E DIAGNÓSTICO POR IMAGEM', 'RADIOLOGIA E DIAGNÓSTICO POR IMAGEM'), ('DIAGNÓSTICO POR IMAGEM', 'DIAGNÓSTICO POR IMAGEM'),
        ('RADIOTERAPIA', 'RADIOTERAPIA'), ('REUMATOLOGIA', 'REUMATOLOGIA'), ('UROLOGIA', 'UROLOGIA')
    ]

class Plano_Saude(models.Model):
    plano = models.CharField(max_length=50)

class Sexo(models.Model):
    SEXO = [
        ('Masculino', 'Masculino'),
        ('Feminino', 'Feminino'),
        ('Outro', 'Outro')
    ]

class Medico(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    especialidade = models.CharField(max_length=50, choices=Especialidade.ESPECIALIDADE)
    sexo = models.CharField(max_length=10, choices=Sexo.SEXO)
    data_nascimento = models.DateField()
    telefone = models.BigIntegerField()
    #planos_aceitos = models.ForeignKey(Plano_Saude, on_delete=models.CASCADE)
    classificacao = models.FloatField(default=0)
    bio = models.CharField(max_length=300, null=True, blank=True)
    foto = models.ImageField(upload_to='medicos_imgs/', blank=True, null=True)