# Generated by Django 3.0.2 on 2020-05-22 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Plano_Saude',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro')], max_length=10)),
                ('data_nascimento', models.DateField()),
                ('telefone', models.BigIntegerField()),
                ('classificacao', models.FloatField(default=0)),
                ('bio', models.CharField(max_length=300)),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ache_medico.Especialidade')),
                ('planos_aceitos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ache_medico.Plano_Saude')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
