# Generated by Django 3.0.2 on 2020-05-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ache_medico', '0005_auto_20200522_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidade',
            field=models.CharField(max_length=50),
        ),
    ]
