# Generated by Django 3.0.2 on 2020-05-22 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ache_medico', '0006_auto_20200522_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='planos_aceitos',
        ),
    ]
