# Generated by Django 3.0.2 on 2020-05-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ache_medico', '0010_medico_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='bio',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
