# Generated by Django 3.0.2 on 2020-05-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ache_medico', '0013_auto_20200527_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
