# Generated by Django 3.0.2 on 2020-05-29 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ache_medico', '0014_medico_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='nome',
        ),
    ]
