# Generated by Django 3.0.2 on 2020-06-01 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ache_medico', '0016_medico_local_de_atendimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='local_de_atendimento',
        ),
    ]
