# Generated by Django 3.0.2 on 2020-06-01 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ache_medico', '0017_remove_medico_local_de_atendimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='local_de_atendimento',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
