# Generated by Django 3.0.2 on 2020-06-01 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ache_medico', '0018_medico_local_de_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='local_de_atendimento',
            field=models.TextField(max_length=300),
        ),
    ]
